### ISSUE TITLE
unexpected keyword argument 'kernel_initializer' for CudnnLSTM

### ISSUE THREAD

**Issue by Chunlinx** [vanzytay/EMNLP2018_NLI#1]
Hi，

Thank you for your work. When I try to run your code, I got an error:
Char CNN Encoder..
Traceback (most recent call last):
  File "train_acc.py", line 752, in <module>
    exp = NLIExperiment(inject_params=None)
  File "train_acc.py", line 151, in __init__
    pos_vocab=len(self.pos_index))
  File "/home/chunlin/exp/NLI/tf_models/model.py", line 74, in __init__
    self.build_graph()
  File "/home/chunlin/exp/NLI/tf_models/model.py", line 1007, in build_graph
    self.prepare_inputs()
  File "/home/chunlin/exp/NLI/tf_models/model.py", line 832, in prepare_inputs
    self.args.cnn_size, self.q1_len)
  File "/home/chunlin/exp/NLI/tf_models/model.py", line 707, in _char_cnn
    rnn_type='LSTM')
  File "/home/chunlin/exp/NLI/tylib/lib/func.py", line 37, in __init__
    1, num_units, kernel_initializer=rnn_init)
TypeError: __init__() got an unexpected keyword argument 'kernel_initializer'

Can you please tell me why this happend?

**Comment by vanzytay** [comment]
hey, i made this repo from copying the code from my main repo. might have some dependency issue (or I copied a wrong version accidentally). Will fix this in the next couple days and push a fix.

Thanks for letting me now.
